// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatController from "./chat_controller"
application.register("chat", ChatController)

import CopyController from "./copy_controller"
application.register("copy", CopyController)

import FeedbackController from "./feedback_controller"
application.register("feedback", FeedbackController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ScrollController from "./scroll_controller"
application.register("scroll", ScrollController)
